import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useFSMStore } from '../store/useFSMStore';
import { FileText, Clock, AlertCircle, Wrench, DollarSign } from 'lucide-react';
import { Avatar } from '../components/ToastNotification';
const StatCard = ({ title, value, icon: Icon, color, trend }) => (_jsxs("div", { className: "bg-white dark:bg-gray-800 p-6 rounded-xl shadow-sm border border-gray-100 dark:border-gray-700", children: [_jsxs("div", { className: "flex items-center justify-between mb-4", children: [_jsx("div", { className: `p-3 rounded-lg ${color}`, children: _jsx(Icon, { className: "w-6 h-6 text-white" }) }), trend && (_jsx("span", { className: "text-xs font-medium text-green-600 dark:text-green-400 bg-green-50 dark:bg-green-900/20 px-2 py-1 rounded-full", children: trend }))] }), _jsx("h3", { className: "text-gray-500 dark:text-gray-400 text-sm font-medium", children: title }), _jsx("p", { className: "text-2xl font-bold text-gray-900 dark:text-gray-100 mt-1", children: value })] }));
const ManagerDashboard = () => {
    const { workOrders, technicians, customers, invoices } = useFSMStore();
    const activeJobs = workOrders.filter(wo => wo.status === 'In Progress').length;
    const pendingJobs = workOrders.filter(wo => wo.status === 'New' || wo.status === 'Assigned').length;
    const completedJobs = workOrders.filter(wo => wo.status === 'Completed').length;
    const availableTechs = technicians.filter(t => t.status === 'Available').length;
    const totalRevenue = invoices
        .filter(inv => inv.status === 'Paid')
        .reduce((acc, inv) => acc + (inv.amount || 0), 0);
    return (_jsxs("div", { className: "space-y-8", children: [_jsxs("div", { children: [_jsx("h1", { className: "text-2xl font-bold text-gray-900 dark:text-gray-100", children: "Dashboard Overview" }), _jsx("p", { className: "text-gray-500 dark:text-gray-400", children: "Welcome back, here's what's happening today." })] }), _jsxs("div", { className: "grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6", children: [_jsx(StatCard, { title: "Active Jobs", value: activeJobs, icon: Clock, color: "bg-blue-500" }), _jsx(StatCard, { title: "Pending Orders", value: pendingJobs, icon: AlertCircle, color: "bg-orange-500" }), _jsx(StatCard, { title: "Available Techs", value: `${availableTechs}/${technicians.length}`, icon: Wrench, color: "bg-purple-500" }), _jsx(StatCard, { title: "Total Revenue", value: `$${totalRevenue.toFixed(2)}`, icon: DollarSign, color: "bg-green-500", trend: "+12%" })] }), _jsxs("div", { className: "grid grid-cols-1 lg:grid-cols-3 gap-8", children: [_jsxs("div", { className: "lg:col-span-2 bg-white dark:bg-gray-800 rounded-xl shadow-sm border border-gray-100 dark:border-gray-700 overflow-hidden", children: [_jsxs("div", { className: "p-6 border-b border-gray-100 dark:border-gray-700 flex justify-between items-center", children: [_jsx("h2", { className: "font-bold text-gray-900 dark:text-gray-100", children: "Recent Work Orders" }), _jsx("a", { href: "./work-orders", className: "text-sm text-blue-600 dark:text-blue-400 hover:text-blue-700 dark:hover:text-blue-300 font-medium", children: "View All" })] }), _jsx("div", { className: "divide-y divide-gray-100 dark:divide-gray-700", children: workOrders.length === 0 ? (_jsxs("div", { className: "p-6 text-center", children: [_jsx(FileText, { className: "w-12 h-12 text-gray-400 dark:text-gray-500 mx-auto mb-3" }), _jsx("p", { className: "text-gray-600 dark:text-gray-400 font-medium", children: "No recent work orders found." })] })) : (workOrders.slice(0, 5).map((wo) => (_jsxs("div", { className: "p-4 hover:bg-gray-50 dark:hover:bg-gray-700 transition-colors flex items-center justify-between", children: [_jsxs("div", { className: "flex items-center gap-4", children: [_jsx("div", { className: `w-2 h-12 rounded-full ${wo.priority === 'Critical' ? 'bg-red-500' :
                                                        wo.priority === 'High' ? 'bg-orange-500' :
                                                            'bg-blue-500'}` }), _jsxs("div", { children: [_jsx("h4", { className: "font-medium text-gray-900 dark:text-gray-100", children: wo.title }), _jsxs("p", { className: "text-sm text-gray-500 dark:text-gray-400", children: [wo.serviceType, " \u2022 ", new Date(wo.scheduledStart).toLocaleDateString()] })] })] }), _jsx("div", { className: "flex items-center gap-4", children: _jsx("span", { className: `px-3 py-1 rounded-full text-xs font-medium ${wo.status === 'Completed' ? 'bg-green-100 dark:bg-green-900/20 text-green-700 dark:text-green-400' :
                                                    wo.status === 'In Progress' ? 'bg-blue-100 dark:bg-blue-900/20 text-blue-700 dark:text-blue-400' :
                                                        'bg-gray-100 dark:bg-gray-700 text-gray-700 dark:text-gray-300'}`, children: wo.status }) })] }, wo.id)))) })] }), _jsxs("div", { className: "bg-white dark:bg-gray-800 rounded-xl shadow-sm border border-gray-100 dark:border-gray-700 overflow-hidden", children: [_jsx("div", { className: "p-6 border-b border-gray-100 dark:border-gray-700", children: _jsx("h2", { className: "font-bold text-gray-900 dark:text-gray-100", children: "Technician Status" }) }), _jsx("div", { className: "p-4 space-y-4", children: technicians.map((tech) => (_jsxs("div", { className: "flex items-center justify-between", children: [_jsxs("div", { className: "flex items-center gap-3", children: [_jsx(Avatar, { src: tech.avatar, name: tech.name, size: 40, showStatus: true, status: tech.status }), _jsxs("div", { children: [_jsx("p", { className: "font-medium text-gray-900 dark:text-gray-100", children: tech.name }), _jsx("p", { className: "text-xs text-gray-500 dark:text-gray-400", children: tech.skills?.join(', ') || 'No skills' })] })] }), _jsx("span", { className: "text-xs text-gray-400 dark:text-gray-500", children: tech.location?.address || 'No location' })] }, tech.id))) })] })] })] }));
};
export default ManagerDashboard;
