import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Search, X, Users, AlertTriangle, CheckCircle, ChevronDown } from 'lucide-react';
export const ScheduleFilterBar = ({ searchTerm, onSearchChange, selectedTechnicians, onTechniciansChange, selectedPriorities, onPrioritiesChange, selectedStatuses, onStatusesChange, technicians, showTechnicianDropdown, onTechnicianDropdownToggle, showPriorityDropdown, onPriorityDropdownToggle, showStatusDropdown, onStatusDropdownToggle, onClearFilters, currentUserRole = 'Manager' }) => {
    const hasActiveFilters = searchTerm || selectedTechnicians.length > 0 || selectedPriorities.length > 0 || selectedStatuses.length > 0;
    return (_jsxs("div", { className: "px-4 pb-4 border-t border-gray-100 pt-4", children: [_jsxs("div", { className: "flex items-center justify-between", children: [_jsxs("div", { className: "flex items-center gap-3 flex-wrap", children: [_jsxs("div", { className: "relative", children: [_jsx(Search, { className: "absolute left-3 top-1/2 transform -translate-y-1/2 w-4 h-4 text-gray-400" }), _jsx("input", { type: "text", placeholder: "Search jobs or locations...", value: searchTerm, onChange: (e) => onSearchChange(e.target.value), className: "pl-10 pr-4 py-2.5 text-sm border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-transparent min-w-[250px] bg-white dark:border-gray-600 dark:bg-gray-800 dark:text-gray-100" })] }), currentUserRole !== 'Technician' && (_jsxs("div", { className: "relative dropdown-container", children: [_jsxs("button", { onClick: () => onTechnicianDropdownToggle(!showTechnicianDropdown), className: "flex items-center gap-2 pl-10 pr-8 py-2.5 text-sm border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-transparent bg-white min-w-[160px] hover:bg-gray-50 dark:border-gray-600 dark:bg-gray-800 dark:text-gray-100", children: [_jsx(Users, { className: "absolute left-3 top-1/2 transform -translate-y-1/2 w-4 h-4 text-gray-400 " }), _jsx("span", { className: "text-gray-700 dark:border-gray-600 dark:bg-gray-800 dark:text-gray-100", children: selectedTechnicians.length > 0
                                                    ? `${selectedTechnicians.length} selected`
                                                    : 'Select technicians...' }), _jsx(ChevronDown, { className: "absolute right-3 top-1/2 transform -translate-y-1/2 w-4 h-4 text-gray-400 pointer-events-none" })] }), showTechnicianDropdown && (_jsx("div", { className: "absolute top-full mt-1 w-full bg-white border border-gray-300 rounded-lg shadow-lg z-50 max-h-48 overflow-y-auto dark:border-gray-600 dark:bg-gray-800 dark:text-gray-100", children: technicians.map(tech => (_jsxs("label", { className: "flex items-center gap-2 px-3 py-2 hover:bg-gray-50 cursor-pointer dark:hover:bg-gray-700", children: [_jsx("input", { type: "checkbox", checked: selectedTechnicians.includes(tech.id), onChange: (e) => {
                                                        if (e.target.checked) {
                                                            onTechniciansChange([...selectedTechnicians, tech.id]);
                                                        }
                                                        else {
                                                            onTechniciansChange(selectedTechnicians.filter(t => t !== tech.id));
                                                        }
                                                    }, className: "w-4 h-4 text-blue-600 bg-gray-100 border-gray-300 rounded focus:ring-blue-500" }), _jsx("span", { className: "text-sm text-gray-700 dark:text-gray-100", children: tech.name })] }, tech.id))) }))] })), _jsxs("div", { className: "relative dropdown-container", children: [_jsxs("button", { onClick: () => onPriorityDropdownToggle(!showPriorityDropdown), className: "flex items-center gap-2 pl-10 pr-8 py-2.5 text-sm border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-transparent bg-white min-w-[140px] hover:bg-gray-50 dark:border-gray-600 dark:bg-gray-800 dark:text-gray-100", children: [_jsx(AlertTriangle, { className: "absolute left-3 top-1/2 transform -translate-y-1/2 w-4 h-4 text-gray-400 dark:border-gray-600 dark:bg-gray-800 dark:text-gray-100" }), _jsx("span", { className: "text-gray-700 dark:text-gray-100", children: selectedPriorities.length > 0
                                                    ? `${selectedPriorities.length} selected`
                                                    : 'Select priorities...' }), _jsx(ChevronDown, { className: "absolute right-3 top-1/2 transform -translate-y-1/2 w-4 h-4 text-gray-400 pointer-events-none dark:border-gray-600 dark:bg-gray-800 dark:text-gray-100" })] }), showPriorityDropdown && (_jsx("div", { className: "absolute top-full mt-1 w-full bg-white border border-gray-300 rounded-lg shadow-lg z-50 max-h-48 overflow-y-auto dark:text-gray-100", children: [
                                            { value: 'Critical', label: 'Critical', color: 'text-red-600' },
                                            { value: 'High', label: 'High', color: 'text-orange-600' },
                                            { value: 'Medium', label: 'Medium', color: 'text-yellow-600' },
                                            { value: 'Low', label: 'Low', color: 'text-green-600' }
                                        ].map(priority => (_jsxs("label", { className: "flex items-center gap-2 px-3 py-2 hover:bg-gray-50 cursor-pointer dark:hover:bg-gray-700 dark:bg-gray-800 dark:text-gray-100", children: [_jsx("input", { type: "checkbox", checked: selectedPriorities.includes(priority.value), onChange: (e) => {
                                                        if (e.target.checked) {
                                                            onPrioritiesChange([...selectedPriorities, priority.value]);
                                                        }
                                                        else {
                                                            onPrioritiesChange(selectedPriorities.filter(p => p !== priority.value));
                                                        }
                                                    }, className: "w-4 h-4 text-blue-600 bg-gray-100 border-gray-300 rounded focus:ring-blue-500 " }), _jsx("span", { className: `text-sm ${priority.color}`, children: priority.label })] }, priority.value))) }))] }), _jsxs("div", { className: "relative dropdown-container", children: [_jsxs("button", { onClick: () => onStatusDropdownToggle(!showStatusDropdown), className: "flex items-center gap-2 pl-10 pr-8 py-2.5 text-sm border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-transparent bg-white min-w-[150px] hover:bg-gray-50 dark:border-gray-600 dark:bg-gray-800 dark:text-gray-100", children: [_jsx(CheckCircle, { className: "absolute left-3 top-1/2 transform -translate-y-1/2 w-4 h-4 text-gray-400" }), _jsx("span", { className: "text-gray-700 dark:text-gray-100", children: selectedStatuses.length > 0
                                                    ? `${selectedStatuses.length} selected`
                                                    : 'Select status...' }), _jsx(ChevronDown, { className: "absolute right-3 top-1/2 transform -translate-y-1/2 w-4 h-4 text-gray-400 pointer-events-none" })] }), showStatusDropdown && (_jsx("div", { className: "absolute top-full mt-1 w-full bg-white border border-gray-300 rounded-lg shadow-lg z-50 max-h-48 overflow-y-auto dark:hover:bg-gray-700 dark:bg-gray-800 dark:text-gray-100", children: [
                                            { value: 'New', label: '⏳ New', color: 'text-gray-600 dark:text-gray-100' },
                                            { value: 'Assigned', label: '📋 Assigned', color: 'text-blue-600' },
                                            { value: 'In Progress', label: '🔄 In Progress', color: 'text-purple-600' },
                                            { value: 'Completed', label: '✅ Completed', color: 'text-green-600' }
                                        ].map(status => (_jsxs("label", { className: "flex items-center gap-2 px-3 py-2 hover:bg-gray-50 cursor-pointer dark:hover:bg-gray-700 dark:bg-gray-800 dark:text-gray-100", children: [_jsx("input", { type: "checkbox", checked: selectedStatuses.includes(status.value), onChange: (e) => {
                                                        if (e.target.checked) {
                                                            onStatusesChange([...selectedStatuses, status.value]);
                                                        }
                                                        else {
                                                            onStatusesChange(selectedStatuses.filter(s => s !== status.value));
                                                        }
                                                    }, className: "w-4 h-4 text-blue-600 bg-gray-100 border-gray-300 rounded focus:ring-blue-500" }), _jsx("span", { className: `text-sm ${status.color}`, children: status.label })] }, status.value))) }))] })] }), hasActiveFilters && (_jsxs("button", { onClick: onClearFilters, className: "flex items-center gap-2 px-4 py-2.5 text-sm text-red-600 hover:text-red-700 hover:bg-red-50 rounded-lg transition-colors border border-red-200 bg-red-25", children: [_jsx(X, { className: "w-4 h-4" }), "Clear All Filters"] }))] }), hasActiveFilters && (_jsxs("div", { className: "flex items-center gap-2 mt-3 flex-wrap", children: [_jsx("span", { className: "text-xs font-medium text-gray-500 uppercase tracking-wide", children: "Active Filters:" }), searchTerm && (_jsxs("span", { className: "inline-flex items-center gap-1 px-2 py-1 text-xs bg-blue-100 text-blue-800 rounded-full", children: ["Search: \"", searchTerm, "\"", _jsx("button", { onClick: () => onSearchChange(''), className: "hover:bg-blue-200 rounded-full p-0.5", children: _jsx(X, { className: "w-3 h-3" }) })] })), selectedTechnicians.length > 0 && (_jsxs("span", { className: "inline-flex items-center gap-1 px-2 py-1 text-xs bg-purple-100 text-purple-800 rounded-full", children: [selectedTechnicians.length, " technician", selectedTechnicians.length > 1 ? 's' : '', _jsx("button", { onClick: () => onTechniciansChange([]), className: "hover:bg-purple-200 rounded-full p-0.5", children: _jsx(X, { className: "w-3 h-3" }) })] })), selectedPriorities.length > 0 && (_jsxs("span", { className: "inline-flex items-center gap-1 px-2 py-1 text-xs bg-orange-100 text-orange-800 rounded-full", children: [selectedPriorities.length, " priorit", selectedPriorities.length > 1 ? 'ies' : 'y', _jsx("button", { onClick: () => onPrioritiesChange([]), className: "hover:bg-orange-200 rounded-full p-0.5", children: _jsx(X, { className: "w-3 h-3" }) })] })), selectedStatuses.length > 0 && (_jsxs("span", { className: "inline-flex items-center gap-1 px-2 py-1 text-xs bg-green-100 text-green-800 rounded-full", children: [selectedStatuses.length, " status", selectedStatuses.length > 1 ? 'es' : '', _jsx("button", { onClick: () => onStatusesChange([]), className: "hover:bg-green-200 rounded-full p-0.5", children: _jsx(X, { className: "w-3 h-3" }) })] }))] }))] }));
};
